keywords: Hexo, BMW

favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

rss: /atom.xml

# 导航栏头部名称
nav_name: GODBMW.com 

# 导航栏：支持标签、分类、友链、关于和自定义页面
nav: 
  - 
    name: 主页
    path: /
    blank: 0
  -
    name: 归档
    path: /archives/
    blank: 0
  -
    name: 分类
    path: /categories/
    blank: 0
  -
    name: 标签
    path: /tags/
    blank: 0
  -
    name: 友链
    path: /friends/
    blank: 0
  - 
    name: 关于
    path: /about/
    blank: 0

leancloud:
  appid: # 填写您的appid
  appkey: # 填写您的appkey
  comment: false # 是否开启评论功能
  timer: false # 是否开启文章统计

# 友链详细信息
friends:
  -
    nickname: GodBMW
    avatar: https://gravatar.loli.net/avatar/b20750c40cd911256ddbd76a7f7e724c?d=robohash&v=1.3.3
    site: https://godbmw.com
    meta: BMW 主题作者