keywords: Hexo, BMW

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

# RSS文件
rss: 

# 自定义样式文件
custom_style: 

# 开启 评论 & 统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
leancloud:
  appid: # 填写您的appid
  appkey: # 填写您的appkey
  comment: false # 是否开启评论系统
  timer: false # 是否开启文章统计

# 导航栏头部名称
nav_name: GODBMW.com 
# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav: 
  - 
    name: 主页
    path: /
  -
    name: 归档
    path: /archives/
  -
    name: 分类
    path: /categories/
  -
    name: 标签
    path: /tags/
  -
    name: 友链
    path: /friends/
  - 
    name: 关于
    path: /about/
  - 
    name: 抓到我
    children:
      -
        name: Github
        path: "https://github.com/dongyuanxin"
        blank: true
      -
        name: "SegmentFault"
        path: "https://segmentfault.com/u/godbmw"
        blank: true

# 友链详细信息
friends:
  -
    nickname: GodBMW # 昵称
    avatar: https://gravatar.loli.net/avatar/b20750c40cd911256ddbd76a7f7e724c # 头像链接
    site: https://godbmw.com # 站点地址
    meta: BMW 主题作者 # 站点描述