nav_name: GODBMW.com

keywords: Hexo, BMW

favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.png

rss: /atom.xml

nav: 
  - 
    name: 主页
    path: /
    blank: 0
  -
    name: 教程
    path: 
    blank: 1
    children:
      - 
        name: "webpack4 系列教程"
        path: "/category/webpack4%20系列教程/"
        blank: 0
      -
        name: "每天一个设计模式"
        path: "/category/每天一个设计模式/"
        blank: 0
  -
    name: 归档
    path: /archives/
    blank: 0
  -
    name: 分类
    path: /categories/
    blank: 0
  -
    name: 标签
    path: /tags/
    blank: 0
  -
    name: 友链
    path: /friends/
    blank: 0
  - 
    name: 关于
    path: /about/
    blank: 0
  -
    name: 开源
    path: 
    blank: 0
    children:
      -
        name: "Theme BMW"
        path: "https://github.com/dongyuanxin/theme-bmw"
        blank: 1
      -
        name: "Music API"
        path: "https://github.com/dongyuanxin/music-api-next"
        blank: 1
      -
        name: "Webpack4 Demos"
        path: "https://github.com/dongyuanxin/webpack-demos"
        blank: 1
      -
        name: "ONE BOOK"
        path: "https://github.com/dongyuanxin/onebook"
        blank: 1
  -
    name: 合作
    path: 
    blank: 0
    children:
      -
        name: "WEB前端教室"
        path: "https://mp.weixin.qq.com/mp/homepage?__biz=MzA3NDE5ODUzNA%3D%3D&hid=6&sn=653a847f8dbe14701d4342329383cb7e"
        blank: 1
  -
    name: 抓到我
    path:
    blank: 0
    children:
      -
        name: Github
        path: "https://github.com/dongyuanxin"
        blank: 1
      -
        name: "SegmentFault"
        path: "https://segmentfault.com/u/godbmw"
        blank: 1
      -
        name: "知乎"
        path: "https://www.zhihu.com/people/godbmw/activities"
        blank: 1
      -
        name: "掘金"
        path: "https://juejin.im/user/5b91fcf06fb9a05d3c7fd4a5"
        blank: 1
      -
        name: "简书"
        path: "https://www.jianshu.com/u/d1570f4a618a"
        blank: 1

valine:
  enable: true
  appid: kHD6VmRIlDXlb0WbexREohX9-gzGzoHsz
  appkey: d5hka85EFAgaOXow6JTl1JU7

timer:
  appid: kHD6VmRIlDXlb0WbexREohX9-gzGzoHsz
  appkey: d5hka85EFAgaOXow6JTl1JU7

friends:
  -
    nickname: GodBMW
    avatar: /images/friends/godbmw.jpeg
    site: https://godbmw.com
    meta: 我自己♪(^∇^*)
    show: true
  -
    nickname: TZLoop
    avatar: /images/friends/whereareyou.jpg
    site: https://www.whereareyou.site/
    meta: 吃鸡是不可能吃鸡的这辈子～
    show: true
  -
    nickname: 菜鸟博客
    avatar: /images/friends/birdteam.png
    site: https://birdteam.net/
    meta: Linux运维工程师相关技术教程
    show: true
  -
    nickname: 猴子星球
    avatar: /images/friends/mr-houzi.png
    site: https://mr-houzi.com
    meta: 最不务正业的程序猿
    show: true
  -
    nickname: hojun
    avatar: /images/friends/hojun.jpg
    site: https://www.hojun.cn/
    meta: 一个好奇的人
    show: true
  -
    nickname: 北乐木兽
    avatar: /images/friends/sunyancun.jpg
    site: https://www.sunyancun.top/
    meta: 超帅气的警察哥哥
    show: true
  -
    nickname: 青南
    avatar: /images/friends/avatar.png
    site: https://www.kingname.info
    meta: 给时光以生命
    show: true
  -
    nickname: 緣來來來
    avatar: /images/friends/fkomm.jpg
    site: https://www.fkomm.cn/
    meta: 宝剑锋从磨励出，梅花香自苦寒来
    show: true
  -
    nickname: mySoul
    avatar: /images/friends/iming.png
    site: https://www.iming.info/
    meta: 一只特立独行的。。。。。。
    show: true
  -
    nickname: Finen
    avatar: /images/friends/finen.png
    site: https://www.finen.top/
    meta: Stay Hungry! Stay Foolish!
    show: true
  -
    nickname: Doublesand
    avatar: /images/friends/doublesand.jpg
    site: https://doublesand.github.io
    meta: 做个独立思考的人
    show: true
  -
    nickname: 陈晓拉尼
    avatar: /images/friends/chenxiaolani.jpeg
    site: https://www.chenxiaolani.com/
    meta: Yesterday u said tomorrow
    show: true
  -
    nickname: 嘉美伯爵
    avatar: /images/friends/gaozhe.ico
    site: https://blog.gaozhe.top
    meta: Like author，like book.
    show: true
  -
    nickname: 纯真年代
    avatar: /images/friends/bblog.ico
    site: http://www.bblog.vip
    meta: 感谢年轻时候的自己
    show: true
  -
    nickname: 隔壁老王的随笔
    avatar: /images/friends/dojay.png
    site: https://dojay.cn/
    meta: 一个喜欢撸猫的前端码农的YY天地
    show: true
  -
    nickname: ChungZH
    avatar: /images/friends/chungzh.jpg
    site: https://chungzh.cn
    meta: 向着梦想加油
    show: true
  -
    nickname: 冷星
    avatar: /images/friends/lengxing.jpg
    site: https://lengxing.club/
    meta: 天道酬勤
    show: true
  -
    nickname: 故事胶片
    avatar: /images/friends/rooon.gif
    site: http://rooon.co/
    meta: 前端小白菜
    show: true
  -
    nickname: 小旋锋
    avatar: /images/friends/laijianfeng.jpg
    site: http://laijianfeng.org/
    meta: 专注于大数据，Java后端类技术分享
    show: true
  -
    nickname: TensorFlow
    avatar: /images/friends/tensorflownews.jpg
    site: http://tensorflownews.com/
    meta: TensorFlow教程、资源，AI交流社区
    show: true
  -
    nickname: 乱码
    avatar: /images/friends/luan.jpg
    site: https://luan.ma/
    meta: 洒道轮香，润花杯满，不似前秋恶。
    show: true
  -
    nickname: 冰水鉴心
    avatar: /images/friends/xq773939719.jpg
    site: https://xq773939719.github.io/
    meta: 软工渣.编程痴.开发宅.系统迷.强迫症.
    show: true
  -
    nickname: ah分享
    avatar: /images/friends/yxlblog.png
    site: https://ah.yxlblog.com/
    meta: 分享技术，资源共享
    show: true
  -
    nickname: CrazyCodes
    avatar: /images/friends/fastrun.jpeg
    site: https://blog.fastrun.cn/
    meta: 记录|分享|开发|学习|中的点点滴滴
    show: true